### ISSUE TITLE
QR-Reference-Type NON, Depitor-Information

### ISSUE THREAD

**Issue by LuckyLukeCH** [docspell/swiss-qr-addon#53]
Hello Eikek,

First of all thank you very much for your work!

We successfully installed Docspell and the QR-Addon which works as expected.
One problem we found is, that with the reference-type "NON", the process stops and no information is read from the QR-Code:

> Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] Detecting QR codes in 1 files
Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] Juli 18, 2023 8:25:19 NACHM. org.apache.pdfbox.pdmodel.font.PDType1Font <init>
Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] WARNUNG: Using fallback font LiberationSans for base font Symbol
Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] Juli 18, 2023 8:25:19 NACHM. org.apache.pdfbox.pdmodel.font.PDType1Font <init>
Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] WARNUNG: Using fallback font LiberationSans for base font ZapfDingbats
Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] Juli 18, 2023 8:25:19 NACHM. org.apache.pdfbox.pdmodel.font.PDType1Font <init>
Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] WARNUNG: Using fallback font LiberationSans for Symbol
Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] Failed to read 1 files
Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] - Invalid reference type: NON
Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] No QR codes found.
Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] Creating result data from 0 qr codes
Di.. 18. Juli 2023, 22:25: >> [swissqr-addon-0.4.0 (err)] Done

We created the following QR-Code with "NON" and attach it:
![QRCode NON](https://github.com/docspell/swiss-qr-addon/assets/20842834/d2d4b912-1dfd-4536-9dba-d3a6d76d65ad)

Additionally it would be very helpful to read out the ultimateDebtor-information for Debitor-Invocies:

> "ultimateDebtor": {
    "addressType": "STRUCTURED",
    "name": "Pia-Maria Rutschmann-Schnyder",
    "streetName": "Grosse Marktgasse",
    "houseNumber": "28",
    "postalCode": "9400",
    "city": "Rorschach",
    "country": "CH"
  },

Is this possible to correct and add? 

Thank you very much for your help and regards
Lukas Gaam

**Comment by eikek** [comment]
Thank you for reporting this! Yes, it's definitely possible to add the other reference type. Thanks for the example, I can add this to the tests. The ultimate debitor should also be easy to add. This would then also go into the notes section of an item (for the docspell plugin).

**Comment by eikek** [comment]
Hi @LuckyLukeCH I think the debitor information is already extracted by this plugin, but not put into the notes of an item in docspell. Is that what you meant?

**Comment by LuckyLukeCH** [comment]
Hi Eikek,

I saw, that you already made the changes, wow!
How can we update the Addon 0.40 on our installation?

Thank you and regards
Lukas Gaam

**Comment by eikek** [comment]
No problem, the changes were really small :) I just released a new version 0.5.0 containing the changes. You can simply use the 0.5.0 version of the plugin now.

**Comment by eikek** [comment]
Oh no, what a silly mistake! thanks for pointing it out. I'll create another release shortly.

**Comment by LuckyLukeCH** [comment]
Hi @eikek 

The new version 0.5.1 works perfect, thank you very much!

Regards
Lukas
